name: ci

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
  steps:
      -name: Checkout
        uses: action/checkout@v4
      
      -name: Setup Node
        uses:action/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      -name: Install deps 
        run: npm ci
      -name: Lint OpenAPI (spectral)
        run: npm run lint:api
      -name: Type-check (Typescript)
        run: npm run typecheck
      -name: Run tests (Jest)
        run: npx jest --ci--runInBand  